import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { createRequire } from 'node:module';
import { execFileSync } from 'node:child_process';
import { afterEach, describe, expect, it, vi } from 'vitest';

const require = createRequire(import.meta.url);
const { createPrerenderExportCopy, ROOT_ENV } = require('../scripts/prerender-export-copy.cjs');
const hook = path.resolve('scripts/prerender-export-copy.cjs');
const roots: string[] = [];
function fixture() {
  const root = fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), 'rewire-prerender-')));
  roots.push(root);
  for (const directory of ['.next/server/app/database/model', 'out/database/model/item'])
    fs.mkdirSync(path.join(root, directory), { recursive: true });
  const source = path.join(root, '.next/server/app/database/model/item.html');
  const destination = path.join(root, 'out/database/model/item/index.html');
  fs.writeFileSync(source, '<html>Exact generated bytes</html>\n');
  return { root, source, destination };
}
afterEach(() => { for (const root of roots.splice(0)) fs.rmSync(root, { recursive: true, force: true }); });

describe('completed app prerender export hardlinks', () => {
  it.each([
    ['database/model/item.html', 'database/model/item/index.html'],
    ['database/model/item.rsc', 'database/model/item/index.txt'],
    ['index.html', 'index.html'],
    ['index.rsc', 'index.txt'],
  ])('links %s to %s and preserves exports when intermediate files are removed', async (from, to) => {
    const f = fixture();
    const source = path.join(f.root, '.next/server/app', from), destination = path.join(f.root, 'out', to);
    fs.writeFileSync(source, 'immutable prerender bytes\n');
    const original = fs.statSync(source);
    await createPrerenderExportCopy({ root: f.root })(source, destination);
    const exported = fs.statSync(destination);
    expect([exported.dev, exported.ino]).toEqual([original.dev, original.ino]);
    expect(fs.readFileSync(destination)).toEqual(fs.readFileSync(source));
    expect(exported.nlink).toBe(2);
    fs.rmSync(path.join(f.root, '.next/server'), { recursive: true });
    expect(fs.readFileSync(destination, 'utf8')).toBe('immutable prerender bytes\n');
  });

  it('keeps the factory isolated and delegates unrelated copies with their original flags', async () => {
    const f = fixture(), native = fs.promises.copyFile;
    const copyFile = vi.fn(async () => undefined);
    const copy = createPrerenderExportCopy({ root: f.root, copyFile });
    const other = [
      [path.join(f.root, 'public/omics/catalogue.json'), path.join(f.root, 'out/omics/catalogue.json')],
      [f.source, path.join(f.root, 'out/unrelated.html')],
      [path.join(f.root, '.next/server/app/item.js'), f.destination],
      [path.join(f.root, '.next/server/app-sibling/item.html'), f.destination],
    ];
    for (const [source, destination] of other) await copy(source, destination, fs.constants.COPYFILE_EXCL);
    expect(copyFile.mock.calls).toEqual(other.map(([source, destination]) => [source, destination, fs.constants.COPYFILE_EXCL]));
    expect(fs.promises.copyFile).toBe(native);
  });

  it.each(['file', 'symlink'])('rejects an existing destination %s without changing either file', async kind => {
    const f = fixture();
    if (kind === 'file') fs.writeFileSync(f.destination, 'preserve destination');
    else fs.symlinkSync(f.source, f.destination);
    const before = fs.readFileSync(f.source);
    await expect(createPrerenderExportCopy({ root: f.root })(f.source, f.destination)).rejects.toThrow('already exists');
    expect(fs.readFileSync(f.source)).toEqual(before);
    if (kind === 'file') expect(fs.readFileSync(f.destination, 'utf8')).toBe('preserve destination');
  });

  it.each(['source-file', 'source-parent', 'destination-parent', 'output-root'])('rejects a symlinked %s', async kind => {
    const f = fixture();
    const target = kind === 'source-file' ? f.source : kind === 'source-parent' ? path.dirname(f.source)
      : kind === 'destination-parent' ? path.dirname(f.destination) : path.join(f.root, 'out');
    const saved = `${target}-saved`;
    fs.renameSync(target, saved); fs.symlinkSync(saved, target);
    await expect(createPrerenderExportCopy({ root: f.root })(f.source, f.destination)).rejects.toThrow('Unsafe');
    expect(fs.existsSync(f.destination)).toBe(false);
  });

  it('rejects relative roots, noncanonical export paths and unsupported copy flags', async () => {
    const f = fixture();
    expect(() => createPrerenderExportCopy({ root: '.' })).toThrow('canonical absolute');
    const copy = createPrerenderExportCopy({ root: f.root });
    await expect(copy(path.dirname(f.source) + '/../model/item.html', f.destination)).rejects.toThrow('Noncanonical');
    await expect(copy(f.source, f.destination, fs.constants.COPYFILE_EXCL)).rejects.toThrow('unsupported copy flags');
    expect(fs.existsSync(f.destination)).toBe(false);
  });

  it('never falls back to a copy when hardlinking fails, including cross-filesystem exports', async () => {
    const f = fixture(), copyFile = vi.fn();
    const link = vi.fn(async () => { throw Object.assign(new Error('cross filesystem'), { code: 'EXDEV' }); });
    await expect(createPrerenderExportCopy({ root: f.root, copyFile, link })(f.source, f.destination)).rejects.toMatchObject({ code: 'EXDEV' });
    expect(copyFile).not.toHaveBeenCalled(); expect(fs.existsSync(f.destination)).toBe(false);
  });

  it('fails closed if another writer creates the destination immediately before linking', async () => {
    const f = fixture(), copyFile = vi.fn();
    const link = async (from: string, to: string) => { fs.writeFileSync(to, 'concurrent output'); await fs.promises.link(from, to); };
    await expect(createPrerenderExportCopy({ root: f.root, copyFile, link })(f.source, f.destination)).rejects.toMatchObject({ code: 'EEXIST' });
    expect(fs.readFileSync(f.destination, 'utf8')).toBe('concurrent output');
    expect(fs.readFileSync(f.source, 'utf8')).toBe('<html>Exact generated bytes</html>\n');
    expect(copyFile).not.toHaveBeenCalled();
  });

  it('rejects unsupported installed Next versions before changing fs in the child', () => {
    const f = fixture();
    fs.mkdirSync(path.join(f.root, 'node_modules/next'), { recursive: true });
    fs.writeFileSync(path.join(f.root, 'node_modules/next/package.json'), '{"version":"15.0.0"}');
    expect(() => execFileSync(process.execPath, ['--require', hook, '-e', 'process.stdout.write("unexpected")'], {
      env: { ...process.env, [ROOT_ENV]: f.root }, stdio: 'pipe',
    })).toThrow('supports Next 14.2.16');
  });

  it('hooks the actual Next export implementation in an isolated Node child', () => {
    const f = fixture(), nextPackage = path.dirname(require.resolve('next/package.json'));
    fs.mkdirSync(path.join(f.root, 'node_modules'), { recursive: true });
    fs.symlinkSync(nextPackage, path.join(f.root, 'node_modules/next'), 'dir');
    const write = (relative: string, value: unknown) => {
      const file = path.join(f.root, relative); fs.mkdirSync(path.dirname(file), { recursive: true });
      fs.writeFileSync(file, typeof value === 'string' ? value : JSON.stringify(value));
    };
    write('.next/BUILD_ID', 'fixture');
    write('.next/server/pages-manifest.json', {});
    write('.next/server/server-reference-manifest.json', { node: {}, edge: {} });
    write('.next/server/next-font-manifest.json', { app: {}, pages: {}, appUsingSizeAdjust: false, pagesUsingSizeAdjust: false });
    write('.next/server/app-paths-manifest.json', { '/database/model/item/page': 'app/database/model/item/page.js', '/page': 'app/page.js' });
    write('.next/app-path-routes-manifest.json', { '/database/model/item/page': '/database/model/item', '/page': '/' });
    write('.next/prerender-manifest.json', { version: 4, routes: {
      '/database/model/item': { srcRoute: '/database/model/item' }, '/': { srcRoute: '/' },
    }, dynamicRoutes: {}, notFoundRoutes: [], preview: {} });
    write('.next/server/app/database/model/item.rsc', 'generated RSC\n');
    write('.next/server/app/index.html', 'generated root HTML\n');
    write('.next/server/app/index.rsc', 'generated root RSC\n');
    const code = `
      const path = require('node:path');
      const root = ${JSON.stringify(f.root)};
      const next = ${JSON.stringify(nextPackage)};
      const { defaultConfig } = require(path.join(next, 'dist/server/config-shared.js'));
      const { trace } = require(path.join(next, 'dist/trace/index.js'));
      const exportApp = require(path.join(next, 'dist/export/index.js')).default;
      exportApp(root, {
        nextConfig: { ...defaultConfig, output: 'export', trailingSlash: true },
        enabledDirectories: { app: true, pages: false }, buildExport: false,
        silent: true, pages: [], outdir: path.join(root, 'out'),
        exportPageWorker: async () => ({}), exportAppPageWorker: async () => ({}),
        endWorker: async () => {},
      }, trace('fixture')).catch(error => { console.error(error); process.exitCode = 1; });
    `;
    execFileSync(process.execPath, ['--require', hook, '-e', code], {
      env: { ...process.env, [ROOT_ENV]: f.root, NEXT_TELEMETRY_DISABLED: '1' }, timeout: 30_000, stdio: 'pipe',
    });
    for (const [from, to] of [
      [f.source, f.destination],
      [f.source.replace(/\.html$/, '.rsc'), f.destination.replace(/\.html$/, '.txt')],
      [path.join(f.root, '.next/server/app/index.html'), path.join(f.root, 'out/index.html')],
      [path.join(f.root, '.next/server/app/index.rsc'), path.join(f.root, 'out/index.txt')],
    ]) {
      expect(fs.readFileSync(to)).toEqual(fs.readFileSync(from));
      expect(fs.statSync(to).ino).toBe(fs.statSync(from).ino);
      expect(fs.statSync(to).nlink).toBe(2);
    }
  });
});
